### ISSUE TITLE
gross mistagging

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_German-GSD#36]
I found a case where `gross` (not `groß`) gets tagged as an `ADV`

Is this a mistag?

```
# sent_id = train-s650
# text = Wie mein Vorposter bereits erwähnt hat, wird hier sehr gross auf den Kundenservice geachtet.
1       Wie     wie     SCONJ   KOUS    _       5       mark    _       _
2       mein    mein    DET     PPOSAT  Case=Nom|Gender=Masc|Number=Sing|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs       3       det:poss        _
_
3       Vorposter       Vorposter       NOUN    NN      Case=Nom|Gender=Neut|Number=Sing        5       nsubj   _       _
4       bereits bereits ADV     ADV     _       5       advmod  _       _
5       erwähnt erwähnen        VERB    VVPP    VerbForm=Part   15      advcl   _       _
6       hat     haben   AUX     VAFIN   Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   5       aux     _       SpaceAfter=No
7       ,       ,       PUNCT   $,      _       5       punct   _       _
8       wird    werden  AUX     VAFIN   Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Pass        15      aux:pass        _       _
9       hier    hier    ADV     ADV     _       15      advmod  _       _
10      sehr    sehr    ADV     ADV     _       11      advmod  _       _
11      gross   groß    ADV     ADJD    _       15      advmod  _       _
12      auf     auf     ADP     APPR    _       14      case    _       _
13      den     der     DET     ART     Case=Acc|Definite=Def|Gender=Masc|Number=Sing|PronType=Art      14      det     _       _
14      Kundenservice   Kundenservice   NOUN    NN      Case=Acc|Gender=Masc|Number=Sing        15      obl     _       _
15      geachtet        achten  VERB    VVPP    VerbForm=Part   0       root    _       SpaceAfter=No
16      .       .       PUNCT   $.      _       15      punct   _       _
```

**Comment by AngledLuffa** [comment]
(in all other cases, `gross` or `groß` get tagged as `ADJ`)

**Comment by amir-zeldes** [comment]
I think this is because it's being used as `advmod` and has the xpos `ADJD`, which means 'predicative or adverbially used adjective', which in German has distinct morphology from an attributive adjective. These adjective forms have no unique suffix, and can be used with copulas or as manner adverbials, similarly to English "it is quick" and "do it quick".

In this particular case, the sentence can be translated with gross as an adverb:

"As the poster before me already mentioned, attention is paid to customer service here in a big way" (gross, lit. "large(ly)", i.e. "big time" or similar). So I think upos ADV is actually reasonable in this context (and essentially always for xpos=ADJD + deprel=advmod)

**Comment by dan-zeman** [comment]
I agree that `ADV` makes some sense with `advmod` but I think it is more practical to keep the word as adjective (which in German can also have the `advmod` function – that is quite fine, also with the validator). The form without agreement suffixes is just one form of the adjectival morphological paradigm.

The current annotation is inconsistent, and it affects many adjectives, not just _gross_. So there definitely is work to be done. I will look into it and I'm leaving the issue open for the time being.

**Comment by dan-zeman** [comment]
Fixed, closing.
